# Generated by Django 5.0.3 on 2024-03-30 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alunos',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='img/alunos'),
        ),
    ]
