# Generated by Django 5.0.3 on 2024-04-07 20:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0003_professor'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Alunos',
            new_name='Aluno',
        ),
        migrations.AlterModelOptions(
            name='aluno',
            options={},
        ),
    ]
