# Generated by Django 5.0.3 on 2024-04-08 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0004_rename_alunos_aluno_alter_aluno_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='professor',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='img/professores'),
        ),
    ]
